[package]
name = "minio-rsc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "^0.14"
chrono = "^0.4"
rust-crypto = "^0.2"
hex = "^0.4.2"